apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-05-26T03:10:14Z"
  labels:
    app: hello-minikube
  name: hello-minikube
  namespace: default
  resourceVersion: "510"
  uid: 18c72450-067a-4b29-8462-30318874eb2b
spec:
  clusterIP: 10.109.116.8
  clusterIPs:
  - 10.109.116.8
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32054
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-minikube
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}